version: 2.1

orbs:
  ruby: circleci/ruby@1.3.0

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:3.0.2
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler --no-document
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec
      - run:
          name: Run Standard
          command: bundle exec standardrb
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
